// data.js

    const units = {
    "kg": { s: "kilogram", pa: "kilogramy", pb: "kilogramów", gs: "kilograma", g: "m", en: "kg" },
    "szt": { s: "sztuka", pa: "sztuki", pb: "sztuk", gs: "sztuki", g: "f", en: "piece" },
    "butelka": { s: "butelka", pa: "butelki", pb: "butelek", gs: "butelki", g: "f", en: "bottle" },
    "lyzka": { s: "łyżka", pa: "łyżki", pb: "łyżek", gs: "łyżki", g: "f", en: "spoon" },
    "lyzeczka": { s: "łyżeczka", pa: "łyżeczki", pb: "łyżeczek", gs: "łyżeczki", g: "f", en: "tsp" },
    "szklanka": { s: "szklanka", pa: "szklanki", pb: "szklanek", gs: "szklanki", g: "f", en: "glass" },
    "bochenek": { s: "bochenek", pa: "bochenki", pb: "bochenków", gs: "bochenka", g: "m", en: "loaf" },
    "opakowanie": { s: "opakowanie", pa: "opakowania", pb: "opakowań", gs: "opakowania", g: "n", en: "pack" },
    "szczypta": { s: "szczypta", pa: "szczypty", pb: "szczypt", gs: "szczypty", g: "f", en: "pinch" },
    "zgrzewka": { s: "zgrzewka", pa: "zgrzewki", pb: "zgrzewek", gs: "zgrzewki", g: "f", en: "multipack" },
    "peczek": { s: "pęczek", pa: "pęczki", pb: "pęczków", gs: "pęczka", g: "m", en: "bunch" },
    "litr": { s: "litr", pa: "litry", pb: "litrów", gs: "litra", g: "m", en: "liter" },
    "kostka": { s: "kostka", pa: "kostki", pb: "kostek", gs: "kostki", g: "f", en: "block" },
    "sloik": { s: "słoik", pa: "słoiki", pb: "słoików", gs: "słoika", g: "m", en: "jar" },
    "gramy": { s: "gram", pa: "gramy", pb: "gramów", gs: "grama", g: "m", en: "g" },
    "kubek": { s: "kubek", pa: "kubki", pb: "kubków", gs: "kubka", g: "m", en: "cup" },
    "puszka": { s: "puszka", pa: "puszki", pb: "puszek", gs: "puszki", g: "f", en: "can" },
    "karton": { s: "karton", pa: "kartony", pb: "kartonów", gs: "kartonu", g: "m", en: "carton" },
    "doniczka": { s: "doniczka", pa: "doniczki", pb: "doniczek", gs: "doniczki", g: "f", en: "pot" },
    "plastry": { s: "plaster", pa: "plastry", pb: "plastrów", gs: "plastra", g: "m", en: "slice" },
    "peto": { s: "pęto", pa: "pęta", pb: "pęt", gs: "pęta", g: "n", en: "coil" },
    "kobialka": { s: "kobiałka", pa: "kobiałki", pb: "kobiałek", gs: "kobiałki", g: "f", en: "basket" },
    "kubek_reg": { s: "zwykły kubek", pa: "zwykłe kubki", pb: "zwykłych kubków", gs: "zwykłego kubka", g: "m", en: "regular cup" },
    "kubek_large": { s: "duży kubek", pa: "duże kubki", pb: "dużych kubków", gs: "dużego kubka", g: "m", en: "large cup" },
    "paleta": { s: "paleta", pa: "palety", pb: "palet", gs: "palety", g: "f", en: "pallet" },
    "worek": { s: "worek", pa: "worki", pb: "worków", gs: "worka", g: "m", en: "bag" },
    "tona": { s: "tona", pa: "tony", pb: "ton", gs: "tony", g: "f", en: "ton" },
    "m2": { s: "metr kwadratowy", pa: "metry kwadratowe", pb: "metrów kwadratowych", gs: "metra kwadratowego", g: "m", en: "sq meter" },
    "m3": { s: "metr sześcienny", pa: "metry sześcienne", pb: "metrów sześciennych", gs: "metra sześciennego", g: "m", en: "cubic meter" },
    "rolka": { s: "rolka", pa: "rolki", pb: "rolek", gs: "rolki", g: "f", en: "roll" },
    "metr": { s: "metr", pa: "metry", pb: "metrów", gs: "metra", g: "m", en: "meter" },
    "tuba": { s: "tuba", pa: "tuby", pb: "tub", gs: "tuby", g: "f", en: "tube" }
};


    const foodDb = [
        // FRUIT
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Jabłko", en: "Apple", gs: "jabłka", g: "n", u: ["kg"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Banan", en: "Banana", gs: "banana", g: "m", u: ["kg"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Gruszka", en: "Pear", gs: "gruszki", g: "f", u: ["kg"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Pomarańcza", en: "Orange", gs: "pomarańczy", g: "f", u: ["kg"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Cytryna", en: "Lemon", gs: "cytryny", g: "f", u: ["szt", "kg"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Winogrona", en: "Grapes", gs: "winogron", g: "n", u: ["kg"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Truskawki", en: "Strawberries", gs: "truskawek", g: "f", u: ["kg", "kobialka"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Maliny", en: "Raspberries", gs: "malin", g: "f", u: ["opakowanie"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Borówki", en: "Blueberries", gs: "borówek", g: "f", u: ["opakowanie"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Arbuz", en: "Watermelon", gs: "arbuza", g: "m", u: ["kg"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Awokado", en: "Avocado", gs: "awokado", g: "n", u: ["szt"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Mango", en: "Mango", gs: "mango", g: "n", u: ["szt"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Śliwki", en: "Śliwek", gs: "śliwek", g: "f", u: ["kg"] },
        { cat: {en:"Fruit", pl:"Owoce"}, pl: "Czereśnie", en: "Sweet cherries", gs: "czereśni", g: "f", u: ["kg"] },

        // VEGETABLES
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Ziemniaki", en: "Potatoes", gs: "ziemniaków", g: "m", u: ["kg"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Marchew", en: "Carrot", gs: "marchwi", g: "f", u: ["kg"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Cebula", en: "Onion", gs: "cebuli", g: "f", u: ["kg"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Czosnek", en: "Garlic", gs: "czosnku", g: "m", u: ["szt"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Pomidor", en: "Tomato", gs: "pomidora", g: "m", u: ["kg"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Ogórek", en: "Cucumber", gs: "ogórka", g: "m", u: ["kg"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Papryka", en: "Bell Pepper", gs: "papryki", g: "f", u: ["kg", "szt"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Kapusta", en: "Cabbage", gs: "kapusty", g: "f", u: ["szt", "kg"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Sałata", en: "Lettuce", gs: "sałaty", g: "f", u: ["szt"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Brokuł", en: "Broccoli", gs: "brokuła", g: "m", u: ["szt"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Kalafior", en: "Cauliflower", gs: "kalafiora", g: "m", u: ["szt"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Rzodkiewka", en: "Radish", gs: "rzodkiewki", g: "f", u: ["peczek"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Szczypiorek", en: "Chives", gs: "szczypiorku", g: "m", u: ["peczek"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Koper", en: "Dill", gs: "kopru", g: "m", u: ["peczek"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Szparagi", en: "Asparagus", gs: "szparagów", g: "m", u: ["peczek"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Kurki", en: "Chanterelles", gs: "kurek", g: "f", u: ["opakowanie", "kg"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Dynia", en: "Pumpkin", gs: "dyni", g: "f", u: ["kg", "szt"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Cukinia", en: "Zucchini", gs: "cukinii", g: "f", u: ["kg", "szt"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Bakłażan", en: "Eggplant", gs: "bakłażana", g: "m", u: ["szt"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Pietruszka", en: "Parsley root", gs: "pietruszki", g: "f", u: ["kg"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Seler", en: "Celeriac", gs: "selera", g: "m", u: ["szt", "kg"] },
        { cat: {en:"Vegetable", pl:"Warzywo"}, pl: "Por", en: "Leek", gs: "pora", g: "m", u: ["szt"] },

        // PANTRY
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Mąka", en: "Flour", gs: "mąki", g: "f", u: ["kg", "szklanka"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Cukier", en: "Sugar", gs: "cukru", g: "m", u: ["kg", "szklanka", "lyzeczka"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Sól", en: "Salt", gs: "soli", g: "f", u: ["kg", "szczypta", "lyzeczka"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Pieprz", en: "Pepper", gs: "pieprzu", g: "m", u: ["opakowanie", "szczypta"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Olej", en: "Oil", gs: "oleju", g: "m", u: ["litr", "lyzka"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Masło", en: "Butter", gs: "masła", g: "n", u: ["kostka", "lyzka"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Ryż", en: "Rice", gs: "ryżu", g: "m", u: ["opakowanie", "szklanka"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Mleko", en: "Milk", gs: "mleka", g: "n", u: ["litr", "szklanka"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Jajka", en: "Eggs", gs: "jajek", g: "n", u: ["szt", "opakowanie"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Miód", en: "Honey", gs: "miodu", g: "m", u: ["sloik", "lyzka"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Drożdże", en: "Yeast", gs: "drożdży", g: "f", u: ["opakowanie", "gramy"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Śmietana", en: "Sour cream", gs: "śmietany", g: "f", u: ["kubek", "lyzka"] },
        { cat: {en:"Pantry", pl:"Spiżarnia"}, pl: "Ocet", en: "Vinegar", gs: "octu", g: "m", u: ["litr", "lyzka"] },

        // HERBS/SPICES
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Majeranek", en: "Marjoram", gs: "majeranku", g: "m", u: ["opakowanie", "szczypta", "lyzeczka"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Lubczyk", en: "Lovage", gs: "lubczyku", g: "m", u: ["peczek", "szczypta"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Liść laurowy", en: "Bay leaf", gs: "liścia laurowego", g: "m", u: ["opakowanie", "szt"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Ziele angielskie", en: "Allspice", gs: "ziela angielskiego", g: "n", u: ["opakowanie", "szt"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Papryka słodka", en: "Sweet paprika", gs: "papryki słodkiej", g: "f", u: ["opakowanie", "lyzeczka"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Kminek", en: "Caraway", gs: "kminku", g: "m", u: ["opakowanie", "lyzeczka"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Gorczyca", en: "Mustard seed", gs: "gorczycy", g: "f", u: ["opakowanie", "lyzeczka"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Tymianek", en: "Thyme", gs: "tymianku", g: "m", u: ["peczek", "szczypta"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Bazylia", en: "Basil", gs: "bazylii", g: "f", u: ["peczek", "doniczka"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Oregano", en: "Oregano", gs: "oregano", g: "n", u: ["opakowanie", "szczypta"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Cynamon", en: "Cinnamon", gs: "cynamonu", g: "m", u: ["opakowanie", "lyzeczka"] },
        { cat: {en:"Herb", pl:"Zioło"}, pl: "Gałka muszkatołowa", en: "Nutmeg", gs: "gałki muszkatołowej", g: "f", u: ["szt", "szczypta"] },

        // OTHERS
        { cat: {en:"Bakery", pl:"Pieczywo"}, pl: "Chleb", en: "Bread", gs: "chleba", g: "m", u: ["bochenek"] },
        { cat: {en:"Bakery", pl:"Pieczywo"}, pl: "Bułka", en: "Bread roll", gs: "bułki", g: "f", u: ["szt"] },
        { cat: {en:"Bakery", pl:"Pieczywo"}, pl: "Chałka", en: "Challah", gs: "chałki", g: "f", u: ["szt"] },
        { cat: {en:"Bakery", pl:"Pieczywo"}, pl: "Drożdżówka", en: "Sweet bun", gs: "drożdżówki", g: "f", u: ["szt"] },
        { cat: {en:"Dairy", pl:"Nabiał"}, pl: "Jogurt", en: "Yogurt", gs: "jogurtu", g: "m", u: ["kubek"] },
        { cat: {en:"Dairy", pl:"Nabiał"}, pl: "Twaróg", en: "Quark", gs: "twarogu", g: "m", u: ["kostka", "opakowanie"] },
        { cat: {en:"Canned", pl:"Puszka"}, pl: "Zupa", en: "Soup", gs: "zupy", g: "f", u: ["puszka", "sloik"] },
        { cat: {en:"Canned", pl:"Puszka"}, pl: "Groszek", en: "Peas", gs: "groszku", g: "m", u: ["puszka", "sloik"] },
        { cat: {en:"Canned", pl:"Puszka"}, pl: "Kukurydza", en: "Corn", gs: "kukurydzy", g: "f", u: ["puszka"] },
        { cat: {en:"Drinks", pl:"Napoje"}, pl: "Woda", en: "Water", gs: "wody", g: "f", u: ["butelka", "zgrzewka"] },
        { cat: {en:"Drinks", pl:"Napoje"}, pl: "Sok", en: "Juice", gs: "soku", g: "m", u: ["karton", "butelka"] },
        { cat: {en:"Alcohol", pl:"Alkohol"}, pl: "Piwo", en: "Beer", gs: "piwa", g: "n", u: ["butelka", "puszka"] },
        { cat: {en:"Alcohol", pl:"Alkohol"}, pl: "Wino", en: "Wine", gs: "wina", g: "n", u: ["butelka"] },
        { cat: {en:"Meat", pl:"Mięso"}, pl: "Szynka", en: "Ham", gs: "szynki", g: "f", u: ["plastry", "kg"] },
        { cat: {en:"Meat", pl:"Mięso"}, pl: "Kiełbasa", en: "Sausage", gs: "kiełbasy", g: "f", u: ["peto", "kg"] },
        { cat: {en:"Meat", pl:"Mięso"}, pl: "Parówki", en: "Frankfurters", gs: "parówek", g: "f", u: ["opakowanie", "kg"] },
        { cat: {en:"Drinks", pl:"Napoje"}, pl: "Kawa", en: "Coffee", gs: "kawy", g: "f", u: ["kubek_reg", "kubek_large"] },
        { cat: {en:"Drinks", pl:"Napoje"}, pl: "Herbata", en: "Tea", gs: "herbaty", g: "f", u: ["kubek_reg", "kubek_large"] },

        // BUILDING MATERIALS
        { cat: {en:"Building", pl:"Budowa"}, pl: "Cegła", en: "Brick", gs: "cegły", g: "f", u: ["szt", "paleta"] },
        { cat: {en:"Building", pl:"Budowa"}, pl: "Cement", en: "Cement", gs: "cementu", g: "m", u: ["worek", "kg"] },
        { cat: {en:"Building", pl:"Budowa"}, pl: "Piasek", en: "Sand", gs: "piasku", g: "m", u: ["kg", "tona"] },
        { cat: {en:"Building", pl:"Budowa"}, pl: "Beton", en: "Concrete", gs: "betonu", g: "m", u: ["m3"] },
        { cat: {en:"Building", pl:"Budowa"}, pl: "Drewno", en: "Wood", gs: "drewna", g: "n", u: ["m3", "szt"] },
        { cat: {en:"Building", pl:"Budowa"}, pl: "Pustak", en: "Hollow block", gs: "pustaka", g: "m", u: ["szt", "paleta"] },

        // FINISHING
        { cat: {en:"Finishing", pl:"Wykończenie"}, pl: "Farba", en: "Paint", gs: "farby", g: "f", u: ["litr", "puszka"] },
        { cat: {en:"Finishing", pl:"Wykończenie"}, pl: "Gips", en: "Gypsum", gs: "gipsu", g: "m", u: ["kg", "worek"] },
        { cat: {en:"Finishing", pl:"Wykończenie"}, pl: "Tynk", en: "Plaster", gs: "tynku", g: "m", u: ["kg", "worek"] },
        { cat: {en:"Finishing", pl:"Wykończenie"}, pl: "Płytki", en: "Tiles", gs: "płytek", g: "f", u: ["m2", "opakowanie"] },
        { cat: {en:"Finishing", pl:"Wykończenie"}, pl: "Panele", en: "Panels", gs: "paneli", g: "m", u: ["m2", "opakowanie"] },
        { cat: {en:"Finishing", pl:"Wykończenie"}, pl: "Tapeta", en: "Wallpaper", gs: "tapety", g: "f", u: ["rolka"] },

        // HARDWARE
        { cat: {en:"Hardware", pl:"Okucia"}, pl: "Śruba", en: "Screw", gs: "śruby", g: "f", u: ["szt", "opakowanie"] },
        { cat: {en:"Hardware", pl:"Okucia"}, pl: "Gwoźdź", en: "Nail", gs: "gwoździa", g: "m", u: ["szt", "kg"] },
        { cat: {en:"Hardware", pl:"Okucia"}, pl: "Klej", en: "Glue", gs: "kleju", g: "m", u: ["litr", "tuba"] },
        { cat: {en:"Hardware", pl:"Okucia"}, pl: "Silikon", en: "Silicone", gs: "silikonu", g: "m", u: ["tuba"] },
        { cat: {en:"Hardware", pl:"Okucia"}, pl: "Pianka", en: "Foam", gs: "pianki", g: "f", u: ["tuba", "puszka"] },

        // ELECTRICAL & TOOLS
        { cat: {en:"Electrical", pl:"Elektryka"}, pl: "Kabel", en: "Cable", gs: "kabla", g: "m", u: ["metr", "rolka"] },
        { cat: {en:"Electrical", pl:"Elektryka"}, pl: "Gniazdko", en: "Socket", gs: "gniazdka", g: "n", u: ["szt"] },
        { cat: {en:"Electrical", pl:"Elektryka"}, pl: "Włącznik", en: "Switch", gs: "włącznika", g: "m", u: ["szt"] },
        { cat: {en:"Tools", pl:"Narzędzia"}, pl: "Młotek", en: "Hammer", gs: "młotka", g: "m", u: ["szt"] },
        { cat: {en:"Tools", pl:"Narzędzia"}, pl: "Wiertarka", en: "Drill", gs: "wiertarki", g: "f", u: ["szt"] },
        { cat: {en:"Tools", pl:"Narzędzia"}, pl: "Łopata", en: "Shovel", gs: "łopaty", g: "f", u: ["szt"] },
        { cat: {en:"Tools", pl:"Narzędzia"}, pl: "Pędzel", en: "Brush", gs: "pędzla", g: "m", u: ["szt"] }
    ];

